name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        # Should be same version as in scripts/bootstrap.sh
        node-version: '16.14.0'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pre-commit
        pre-commit install -f --install-hooks
        # Should be same version as in scripts/bootstrap.sh
        yarn global add @vue/cli@v4.5.15
        yarn install --ignore-engines

    - name: Lint
      run: pre-commit run -a
