name: Build

on:
  push:
  pull_request:

jobs:
  build_apps-bundle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          # Should be same version as in scripts/bootstrap.sh
          node-version: '16.14.0'

      - name: Install dependencies
        run: |
          # Should be same version as in scripts/bootstrap.sh
          yarn global add @vue/cli@v4.5.15
          yarn install --ignore-engines

      - name: Build
        run: yarn build:apps

      - name: Deploy apps
        run: yarn deploy:apps

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            apps-bundle.zip
            packages/welcome-screen/welcome-screen.zip
