name: Build

on:
  push:
  pull_request:
  workflow_call:
    inputs:
      tagname:
        description: 'The git tag name for release'
        default: ''
        required: true
        type: string
  workflow_dispatch:

jobs:
  build_apps-bundle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout from none-workflow_call
        uses: actions/checkout@v3
        if: ${{ !startsWith(inputs.tagname, 'v') }}

      - name: Checkout from workflow_call
        uses: actions/checkout@v3
        if: startsWith(inputs.tagname, 'v')
        with:
          ref: ${{ inputs.tagname }}

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          # Should be same version as in scripts/bootstrap.sh
          node-version: '16.14.0'

      - name: Install dependencies
        run: |
          # Should be same version as in scripts/bootstrap.sh
          yarn global add @vue/cli@v4.5.15
          yarn install --ignore-engines

      - name: Build
        run: yarn build:apps

      - name: Deploy apps
        run: yarn deploy:apps

      - name: Release when triggered from a tag push
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          files: |
            apps-bundle.zip
            packages/welcome-screen/welcome-screen.zip

      - name: Release when triggered from workflow_call
        uses: softprops/action-gh-release@v1
        if: startsWith(inputs.tagname, 'v')
        with:
          tag_name: ${{ inputs.tagname }}
          generate_release_notes: true
          files: |
            apps-bundle.zip
            packages/welcome-screen/welcome-screen.zip


  build_kolibri-explore-plugin_whl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout from none-workflow_call
        uses: actions/checkout@v3
        if: ${{ !startsWith(inputs.tagname, 'v') }}

      - name: Checkout from workflow_call
        uses: actions/checkout@v3
        if: startsWith(inputs.tagname, 'v')
        with:
          ref: ${{ inputs.tagname }}

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          # Should be same version as in scripts/bootstrap.sh
          node-version: '16.14.0'

      - name: Install latest pipenv
        run: |
          python3 -m pip install --upgrade pipenv

      - name: Install dependencies in pipenv
        run: |
          sh ./scripts/bootstrap.sh

      - name: Build
        run: |
          pipenv run yarn build-dist
          ls -l dist/

      - name: Release to PyPI
        if: startsWith(github.ref, 'refs/tags/') || startsWith(inputs.tagname, 'v')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
